"""empty message

Revision ID: 1b900311056a
Revises: 14940931b07f
Create Date: 2024-10-08 22:02:01.748865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b900311056a'
down_revision = '14940931b07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_machine', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_machine', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
