"""empty message

Revision ID: 47d1b5060875
Revises: 83665e419eeb
Create Date: 2025-04-01 22:33:02.696622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d1b5060875'
down_revision = '83665e419eeb'
branch_labels = None
depends_on = None
import App

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('o_index', App.models.Material.Workpiece.JSONEncodedDict(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_column('o_index')

    # ### end Alembic commands ###
