"""empty message

Revision ID: 74b989751334
Revises: 1b900311056a
Create Date: 2024-10-09 01:15:21.055671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b989751334'
down_revision = '1b900311056a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_machine', schema=None) as batch_op:
        batch_op.drop_index('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_machine', schema=None) as batch_op:
        batch_op.create_index('time', ['time'], unique=False)

    # ### end Alembic commands ###
