"""empty message

Revision ID: 7bc517b131a5
Revises: c16477c37b7d
Create Date: 2024-10-13 17:47:06.794695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bc517b131a5'
down_revision = 'c16477c37b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basemachine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('base_machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_machine',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', mysql.FLOAT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('basemachine')
    # ### end Alembic commands ###
