"""empty message

Revision ID: 83665e419eeb
Revises: 0d4684116ddb
Create Date: 2025-04-01 22:24:28.248414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import json
# revision identifiers, used by Alembic.
revision = '83665e419eeb'
down_revision = '0d4684116ddb'
branch_labels = None
depends_on = None


# 在迁移文件顶部添加自定义类型定义
class JSONEncodedDict(sa.TypeDecorator):
    impl = sa.VARCHAR(255)

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = json.dumps(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = json.loads(value)
        return value

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.alter_column('o_time',
               existing_type=mysql.INTEGER(),
               type_=JSONEncodedDict(),
               existing_nullable=True)
        batch_op.alter_column('o_machine_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=JSONEncodedDict(),
               existing_nullable=True)
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('operation') as batch_op:
        batch_op.alter_column('o_machine_name',
               existing_type=JSONEncodedDict(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('o_time',
               existing_type=JSONEncodedDict(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
