"""empty message

Revision ID: af33749d3629
Revises: cb48e7c3dcb4
Create Date: 2025-04-01 16:06:12.043333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af33749d3629'
down_revision = 'cb48e7c3dcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('workpiece',
    # sa.Column('j_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('j_quantity', sa.Integer(), nullable=False),
    # sa.Column('p_number', sa.String(length=20), nullable=True),
    # sa.Column('c_name', sa.String(length=20), nullable=True),
    # sa.Column('j_number', sa.String(length=20), nullable=False),
    # sa.Column('j_state', sa.String(length=20), nullable=True),
    # sa.Column('j_create_date', sa.DateTime(), nullable=True),
    # sa.Column('j_due_date', sa.DateTime(), nullable=True),
    # sa.Column('j_remark', sa.String(length=32), nullable=True),
    # sa.PrimaryKeyConstraint('j_id')
    # )
    # op.create_table('operation',
    # sa.Column('o_id', sa.Integer(), nullable=False),
    # sa.Column('o_job_id', sa.Integer(), nullable=True),
    # sa.Column('o_time', sa.Integer(), nullable=True),
    # sa.Column('o_machine_name', sa.String(length=20), nullable=True),
    # sa.ForeignKeyConstraint(['o_job_id'], ['workpiece.j_id'], ),
    # sa.PrimaryKeyConstraint('o_id')
    # )
    # op.drop_table('basematerial')
    # op.drop_table('publisher')
    # op.drop_table('book_publisher')
    # op.drop_table('book')
    # op.drop_table('author')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='book_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('book_publisher',
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publisher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_publisher_ibfk_1'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name='book_publisher_ibfk_2'),
    sa.PrimaryKeyConstraint('book_id', 'publisher_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('publisher',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('basematerial',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('sum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('operation')
    op.drop_table('workpiece')
    # ### end Alembic commands ###
