"""empty message

Revision ID: e4198afb1918
Revises: 7bc517b131a5
Create Date: 2025-03-31 22:37:12.479687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4198afb1918'
down_revision = '7bc517b131a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_machine',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False, comment='机床ID'),
    sa.Column('m_number', sa.String(length=20), nullable=False, comment='机床编码'),
    sa.Column('m_name', sa.String(length=20), nullable=False, comment='机床名称'),
    sa.Column('m_state', sa.String(length=20), nullable=False, comment='机床状态'),
    sa.Column('m_time', sa.Float(), nullable=True, comment='累计运行时间(小时)'),
    sa.Column('m_workshop', sa.String(length=20), nullable=False, comment='所在车间'),
    sa.PrimaryKeyConstraint('m_id'),
    sa.UniqueConstraint('m_number')
    )
    op.create_table('basematerial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('basemachine')
    with op.batch_alter_table('mac2', schema=None) as batch_op:
        batch_op.drop_index('time')

    op.drop_table('mac2')
    with op.batch_alter_table('mac1', schema=None) as batch_op:
        batch_op.drop_index('time')

    op.drop_table('mac1')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index('time')

    op.drop_table('material')
    with op.batch_alter_table('mac3', schema=None) as batch_op:
        batch_op.drop_index('time')

    op.drop_table('mac3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mac3',
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('material', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mac3', schema=None) as batch_op:
        batch_op.create_index('time', ['time'], unique=False)

    op.create_table('material',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', mysql.FLOAT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machine', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index('time', ['time'], unique=False)

    op.create_table('mac1',
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('material', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mac1', schema=None) as batch_op:
        batch_op.create_index('time', ['time'], unique=False)

    op.create_table('mac2',
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('material', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mac2', schema=None) as batch_op:
        batch_op.create_index('time', ['time'], unique=False)

    op.create_table('basemachine',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('basematerial')
    op.drop_table('base_machine')
    # ### end Alembic commands ###
